name: Behavior Bug or Plugin Incompatibility
description: Report issues with plugin incompatbility or other behavior related issues.
labels: [ ]
body:
  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin and Datapack List
      description: |
        All plugins and datapacks running on your server.
        To list plugins, run `/plugins`. For datapacks, run `/datapack list`.
    validations:
      required: true

  - type: textarea
    attributes:
      label: MultiPaper version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
        [20:34:42 INFO]: This server is running Paper version git-Paper-540 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
        [20:34:42 INFO]: Checking version, please wait...
        [20:34:42 INFO]: Previous version: git-Paper-538 (MC: 1.16.5)
        [20:34:42 INFO]: You are running the latest version
        ```

        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before submitting this issue, please ensure the following:

        1. You are running the latest version of MultiPaper from [our downloads page](https://multipaper.io/download.html).
        2. You searched for and ensured there isn't already an open issue regarding this.
        3. Your version of Minecraft is supported by MultiPaper.
        4. The bug is not reproducible on Paper.
